name: Build
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.info.outputs.tag }}
      revision: ${{ steps.info.outputs.revision }}
      reponame: ${{ steps.info.outputs.reponame }}
      reponame_lowercase: ${{ steps.info.outputs.reponame_lowercase }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract commit info
        id: info
        run: |
          tag="$(git describe --tags 2>/dev/null)" || true
          date="$(git log -1 --pretty='format:%cd' --date=short 2>/dev/null)"
          hash="$(git log -1 --pretty='format:%h' 2>/dev/null)"
          test "$tag" && revision="$tag-$hash" || revision="$date-$hash"
          echo "::set-output name=tag::$tag"
          echo "::set-output name=revision::$revision"
          test "$reponame" || reponame="${GITHUB_REPOSITORY##*/}"
          test "$reponame_lowercase" || reponame_lowercase="${reponame,,}"
          echo "::set-output name=reponame::$reponame"
          echo "::set-output name=reponame_lowercase::$reponame_lowercase"

      - name: Download NjuPsHwApi
        run: |
          APIVERSION="$(cat APIVERSION.txt)"
          wget "https://github.com/Undefined01/NjuPsHwServer/releases/download/${APIVERSION}/ts-client.zip"
          unzip ts-client.zip

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./deployment/Dockerfile
          build-args: REVISION=${{ steps.info.outputs.revision }}
          tags: |
            ${{ steps.info.outputs.reponame_lowercase }}:${{ steps.info.outputs.revision }}
