name: Build and Deploy to Kubernetes
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

defaults:
  run:
    shell: bash

env:
  deploy_environment: >
    {
      "refs/heads/main": "prod",
      "refs/heads/develop": "dev"
    }

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.info.outputs.tag }}
      revision: ${{ steps.info.outputs.revision }}
      reponame: ${{ steps.info.outputs.reponame }}
      reponame_lowercase: ${{ steps.info.outputs.reponame_lowercase }}
      deploy_environment: ${{ steps.info.outputs.deploy_environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract commit info
        id: info
        run: |
          tag="$(git describe --tags 2>/dev/null)" || true
          date="$(git log -1 --pretty='format:%cd' --date=short 2>/dev/null)"
          hash="$(git log -1 --pretty='format:%h' 2>/dev/null)"
          test "$tag" && revision="$tag-$hash" || revision="$date-$hash"
          echo "tag=$tag"
          echo "revision=$revision"
          echo "deploy_environment=$(echo '${{ env.deploy_environment }}' | jq -r '."${{ github.ref }}"')"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "revision=$revision" >> "$GITHUB_OUTPUT"
          echo "deploy_environment=$(echo '${{ env.deploy_environment }}' | jq -r '."${{ github.ref }}"')" >> "$GITHUB_OUTPUT"
          test "$reponame" || reponame="${GITHUB_REPOSITORY##*/}"
          test "$reponame_lowercase" || reponame_lowercase="${reponame,,}"
          echo "reponame=$reponame"
          echo "reponame_lowercase=$reponame_lowercase"
          echo "reponame=$reponame" >> "$GITHUB_OUTPUT"
          echo "reponame_lowercase=$reponame_lowercase" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'

      - name: Download NjuPsHwApi
        run: |
          APIVERSION="$(cat APIVERSION.txt)"
          wget "https://github.com/Undefined01/NjuPsHwServer/releases/download/${APIVERSION}/ts-client.zip"
          unzip ts-client.zip

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./deployment/Dockerfile
          build-args: REVISION=${{ steps.info.outputs.revision }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.info.outputs.reponame_lowercase }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.info.outputs.reponame_lowercase }}:${{ steps.info.outputs.revision }}

  deploy:
    needs: build
    if: ${{ needs.build.outputs.deploy_environment != 'null' }}
    runs-on: ubuntu-latest
    environment: ${{ needs.build.outputs.deploy_environment }}
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          manifests: |
            deployment/deployment.yml
            deployment/service.yml
          images:
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.build.outputs.reponame_lowercase }}:${{ needs.build.outputs.revision }}
